//! Recognized object keys shared by the parser and the generated tooling contract.
//! These are grammar nodes, not JSON Schema: value and activation rules remain in the parser.

#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct ObjectFields {
    pub id: &'static str,
    pub context: &'static str,
    pub fields: &'static [&'static str],
    pub notes: &'static str,
}

macro_rules! objects {
    ($($name:ident: ($context:literal, [$($field:literal),* $(,)?], $notes:literal)),* $(,)?) => {
        $(pub(crate) const $name: ObjectFields = ObjectFields {
            id: stringify!($name), context: $context, fields: &[$($field),*], notes: $notes,
        };)*
        pub(crate) const OBJECTS: &[&ObjectFields] = &[$(&$name),*];
    };
}

objects! {
    BALANCER: ("$.routing.balancers[]",
        ["tag", "selector", "strategy", "fallbackTag"],
        "Value types, bounds and activation rules are enforced by the executable parser."),
    BALANCER_STRATEGY: ("$.routing.balancers[].strategy",
        ["type", "settings"],
        "random, roundRobin, leastPing and leastLoad only; settings are interpreted according to the selected strategy."),
    DNS: ("$.dns",
        ["fakeIp", "servers", "hosts", "tag", "queryStrategy", "disableCache", "serveStale", "serveExpiredTTL", "disableFallback", "disableFallbackIfMatch"],
        "At most eight servers. Managed selection, cache/fallback policy and IPv4 fake IP only. Hosts and server URL semantics require the executable validator."),
    DNS_OUTBOUND: ("$.outbounds[].settings (dns)",
        ["rewriteNetwork", "rewriteAddress", "rewritePort", "network", "address", "port", "userLevel", "rules", "nonIPQuery", "blockTypes"],
        "network/address/port aliases override rewrite* values. Deprecated nonIPQuery/blockTypes cannot be combined with rules."),
    DNS_RULE: ("$.outbounds[].settings.rules[] (dns)",
        ["action", "qType", "qtype", "domain", "rCode"],
        "qType accepts numeric or range-string selectors. qtype and Reject are deprecated aliases with warnings; qType/qtype cannot both be non-null."),
    DNS_SERVER: ("$.dns.servers[] (object entries)",
        ["address", "port", "domains", "expectedIPs", "expectIPs", "unexpectedIPs", "tag", "timeoutMs", "skipFallback", "queryStrategy", "finalQuery"],
        "expectedIPs is an alias of expectIPs. URL, address/port, query-family and domain/IP-filter combinations are checked by the parser."),
    FAKE_IP: ("$.dns.fakeIp",
        ["enabled", "ipv4Pool", "poolSize", "ttl"],
        "IPv4 only. Positive poolSize must fit the usable pool after reserved addresses; ttl is positive."),
    FINALMASK: ("streamSettings.finalmask",
        ["tcp", "udp", "quicParams"],
        "tcp and udp masks accept only null or empty arrays; nonempty masks are unsupported."),
    FREEDOM_SETTINGS: ("$.outbounds[].settings (freedom)",
        [],
        "Only an empty settings object is supported."),
    GRPC: ("streamSettings.grpcSettings",
        ["authority", "serviceName", "multiMode", "user_agent", "idle_timeout", "health_check_timeout", "permit_without_stream", "initial_windows_size"],
        "Timeout/window numbers are i32 clamped at zero. Header validity and Vision combinations also require core compilation."),
    HAPPY_EYEBALLS: ("streamSettings.sockopt.happyEyeballs",
        ["prioritizeIPv6", "interleave", "tryDelayMs", "maxConcurrentTry"],
        "Opt-in raw TCP race. tryDelayMs=0 disables it; bounds and transport combinations are validated."),
    HTTPUPGRADE: ("streamSettings.httpupgradeSettings",
        ["path", "host", "headers", "acceptProxyProtocol"],
        "acceptProxyProtocol is ignored on the client. headers must not contain Host. REALITY is unsupported."),
    HTTP_SETTINGS: ("$.inbounds[].settings (http)",
        ["timeout", "accounts", "allowTransparent", "userLevel", "allowUnauthenticatedLan"],
        "accounts must be empty; allowTransparent cannot be true. timeout is accepted for compatibility."),
    INBOUND: ("$.inbounds[]",
        ["tag", "protocol", "listen", "port", "settings", "sniffing"],
        "socks, http and tun. Only loopback listeners unless allowUnauthenticatedLan is explicitly true. TUN settings have a separate compatibility surface."),
    LEAST_LOAD: ("$.routing.balancers[].strategy.settings (leastLoad)",
        ["expected", "maxRTT", "tolerance", "baselines", "costs"],
        "Value types, bounds and activation rules are enforced by the executable parser."),
    LEAST_LOAD_COST: ("$.routing.balancers[].strategy.settings.costs[]",
        ["regexp", "match", "value"],
        "Literal substring costs only; regexp=true is unsupported."),
    MUX: ("$.outbounds[].mux",
        ["enabled", "concurrency"],
        "enabled must be absent or false. concurrency is checked as u32 but does not enable mux."),
    OBSERVATORY: ("$.observatory",
        ["subjectSelector", "probeURL", "probeInterval", "enableConcurrency"],
        "Value types, bounds and activation rules are enforced by the executable parser."),
    OUTBOUND: ("$.outbounds[]",
        ["tag", "protocol", "settings", "streamSettings", "mux", "proxySettings", "sendThrough"],
        "freedom, dns and vless only. sendThrough is rejected whenever present, including null. First outbound is the default. Tag graph validation is a later core compilation step."),
    POLICY: ("$.policy",
        ["levels", "system"],
        "Value types, bounds and activation rules are enforced by the executable parser."),
    POLICY_LEVEL: ("$.policy.levels.*",
        ["handshake", "connIdle", "uplinkOnly", "downlinkOnly", "statsUserUplink", "statsUserDownlink", "bufferSize"],
        "Value types, bounds and activation rules are enforced by the executable parser."),
    POLICY_SYSTEM: ("$.policy.system",
        ["statsInboundUplink", "statsInboundDownlink", "statsOutboundUplink", "statsOutboundDownlink"],
        "Flags are modeled for compatibility; this is not the Xray statistics service."),
    PROXY: ("$.outbounds[].proxySettings",
        ["tag", "transportLayer"],
        "Requires nonempty tag and transportLayer=true. REALITY chains fail parsing; missing targets, cycles and additional carrier constraints are validated by core compilation."),
    QUIC_PARAMS: ("streamSettings.finalmask.quicParams",
        ["congestion", "debug", "bbrProfile", "brutalUp", "brutalDown", "udpHop", "initStreamReceiveWindow", "maxStreamReceiveWindow", "initConnectionReceiveWindow", "maxConnectionReceiveWindow", "maxIdleTimeout", "keepAlivePeriod", "disablePathMTUDiscovery", "maxIncomingStreams"],
        "Phase-one XHTTP H3 subset only. Values and cross-field bounds are checked by the parser and carrier compilation; listing a field does not enable every upstream profile."),
    RAW: ("streamSettings.tcpSettings; streamSettings.rawSettings",
        ["header", "acceptProxyProtocol"],
        "acceptProxyProtocol is ignored on the client."),
    RAW_HEADER: ("tcpSettings.header; rawSettings.header",
        ["type", "request", "response"],
        "type may be absent, empty or none; request and response are ignored."),
    ROOT: ("$",
        ["log", "inbounds", "outbounds", "routing", "observatory", "dns", "policy"],
        "log is accepted and ignored. Missing/non-array inbounds and outbounds currently normalize to empty lists. Non-object JSON roots also normalize to an empty model. Parse success alone does not establish runtime usability."),
    ROUTING: ("$.routing",
        ["domainStrategy", "rules", "balancers"],
        "AsIs, IPIfNonMatch and IPOnDemand. Ordered field rules and bounded balancers only."),
    ROUTING_RULE: ("$.routing.rules[]",
        ["type", "inboundTag", "network", "port", "domain", "domains", "ip", "outboundTag", "balancerTag", "ruleTag"],
        "Supports field rules only; domains is an alias of domain. Exactly one outboundTag or balancerTag target. Domain/geodata, compact port selectors and aggregate budgets are validated."),
    SNIFFING: ("$.inbounds[].sniffing",
        ["enabled", "destOverride", "metadataOnly", "routeOnly", "domainsExcluded", "excludedDomains"],
        "domainsExcluded rejects nonempty arrays; excludedDomains is ignored after string-array validation. destOverride supports http, tls and quic when enabled."),
    SOCKOPT: ("streamSettings.sockopt",
        ["happyEyeballs"],
        "Value types, bounds and activation rules are enforced by the executable parser."),
    SOCKS_SETTINGS: ("$.inbounds[].settings (socks)",
        ["auth", "accounts", "udp", "ip", "userLevel", "allowUnauthenticatedLan"],
        "auth must be noauth. accounts must be an empty array when present. ip is ignored; udp and userLevel are parsed."),
    STREAM: ("$.outbounds[].streamSettings; XHTTP downloadSettings after removing address/port",
        ["method", "network", "security", "tlsSettings", "realitySettings", "tcpSettings", "rawSettings", "wsSettings", "httpupgradeSettings", "grpcSettings", "xhttpSettings", "splithttpSettings", "finalmask", "sockopt"],
        "method takes priority over network. raw/tcp, ws/websocket, httpupgrade, grpc, xhttp/splithttp; security none/tls/reality. Carrier/security combinations and inactive block handling require the validator."),
    TLS: ("streamSettings.tlsSettings",
        ["serverName", "allowInsecure", "fingerprint", "alpn", "pinnedPeerCertSha256", "verifyPeerCertByName"],
        "allowInsecure=true is rejected. fromMitm is unsupported. Fingerprints, certificate pins and name constraints use parser validation."),
    UDP_HOP: ("streamSettings.finalmask.quicParams.udpHop",
        ["ports", "interval"],
        "The parser models numeric and comma/range ports, but core carrier compilation rejects nonempty hopping. Empty/default ports are the supported runtime subset."),
    VLESS: ("$.outbounds[].settings (vless)",
        ["vnext"],
        "Exactly one vnext server is required."),
    VLESS_SERVER: ("$.outbounds[].settings.vnext[0]",
        ["address", "port", "users"],
        "Nonempty address, port 1..65535 and at least one UUID user. Unencrypted public-address destinations are rejected."),
    VLESS_USER: ("$.outbounds[].settings.vnext[0].users[]",
        ["id", "encryption", "flow", "level", "email", "security"],
        "Runtime selects the first user. encryption defaults to none; non-none uses the bounded VLESS encryption parser. flow supports empty, xtls-rprx-vision and xtls-rprx-vision-udp443. email is ignored; security is type-checked but ignored."),
    WEBSOCKET: ("streamSettings.wsSettings",
        ["path", "host", "headers", "acceptProxyProtocol", "heartbeatPeriod"],
        "acceptProxyProtocol is ignored on the client. Host headers are normalized with a deprecation warning. REALITY is unsupported."),
    XHTTP: ("streamSettings.xhttpSettings; splithttpSettings; effective extra replacement",
        ["host", "path", "mode", "headers", "xPaddingBytes", "xPaddingObfsMode", "xPaddingKey", "xPaddingHeader", "xPaddingPlacement", "xPaddingMethod", "uplinkHTTPMethod", "sessionIDPlacement", "sessionIDKey", "sessionIDTable", "sessionIDLength", "seqPlacement", "seqKey", "uplinkDataPlacement", "uplinkDataKey", "uplinkChunkSize", "noGRPCHeader", "noSSEHeader", "scMaxEachPostBytes", "scMinPostsIntervalMs", "scMaxConcurrentPosts", "scMaxBufferedPosts", "scStreamUpServerSecs", "serverMaxHeaderBytes", "xmux", "downloadSettings", "extra"],
        "extra replaces rather than merges outer values except host/path/mode. Nested extra is inert. downloadSettings supports an independent XHTTP stack for packet-up/stream-up only; no recursive download. scMaxConcurrentPosts is ignored with a warning."),
    XMUX: ("xhttpSettings.xmux; splithttpSettings.xmux; effective extra.xmux",
        ["maxConcurrency", "maxConnections", "cMaxReuseTimes", "hMaxRequestTimes", "hMaxReusableSecs", "hKeepAlivePeriod"],
        "Positive maxConnections and maxConcurrency are mutually exclusive. Ranges and default/zero semantics require parser validation."),
}
